# Generated by Django 3.1.5 on 2021-01-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Author name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Category name')),
                ('facebook', models.URLField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('site_web', models.URLField(blank=True, max_length=100, null=True, verbose_name='Site web')),
                ('email', models.EmailField(max_length=100, verbose_name='Category name')),
                ('state', models.BooleanField(default=True, verbose_name='Author state')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Cretion date')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('state', models.BooleanField(default=True, verbose_name='Category state')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Cretion date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
